### ISSUE TITLE
Inner Div styles can't be overwritten when using percentages

### ISSUE THREAD

**Issue by shammai** [gdepourtales/ng-cells#14]
The inner div created within each cell (div cell-content or custom-cell-template etc.) has the styles of the td added to them.
However, when using styles such as width if you specify the width in percentages then the inner div gets the same value.  
Therefore, if the td width is 20% wide, then the inner div style will get 20% width.
The problem with this approach is that the inner div percentage is relative to the TD and is therefore too small.

**Comment by gdepourtales** [comment]
No update so closing
