### ISSUE TITLE
Question: Scrollbars on the main window.

### ISSUE THREAD

**Issue by mato75** [gdepourtales/ng-cells#19]
Really like it. 

Question: How would I use this, so that the scrollbars are not on the table itself, but on the main window, so lets say, table (400x400, top: 200, left: 300) and window (1200X720, document width/height includes tables actual width/height, 5000x6000). And I want to scroll thought table with main scrollbars of the window.

**Comment by gdepourtales** [comment]
I guess this has been solved.
