### ISSUE TITLE
Horizontal scroll acts strange when you scroll to the very right

### ISSUE THREAD

**Issue by mato75** [gdepourtales/ng-cells#21]
When scrolling horizontally, sometimes the scroller starts to act strange, but that happens only when you scroll to the very right.

I am using 0.3.3 version, because of the smooth scrolling, but I got this issue also with the new version.

You can check the demo: test/test-noscroll.html (no vertical scroll)

Here is a video:
http://screencast.com/t/WmtmmPWa8mmG

**Comment by gdepourtales** [comment]
In version 0.4.0 the scrollbars are totally redesigned. You should not experience the behaviour of 0.3.x version again.
