### ISSUE TITLE
table scrollbar does not appear on iPad safari

### ISSUE THREAD

**Issue by softweave** [gdepourtales/ng-cells#23]
I wrote a simple app using ng-cells. It works well in Chrome, FireFox and Safari under Mac OS. The scrollbar fails to appear in iPad Safari.

**Comment by clexit** [comment]
It's not just iPad, but any Mac OS. I have no scrollbars on Yosemite, because I use Magic Trackpad and not a mouse, thus cannot scroll any ng-cells tables.

**Comment by gdepourtales** [comment]
The new 0.4.0 version now supports showing the scrollbars on iPads and MacBooks. The behaviour with MacBook trackpad works with both vertical and horizontal scroll.
