### ISSUE TITLE
Mousewheel scrolling not working on FireFox & Safari (Windows 8.1)

### ISSUE THREAD

**Issue by bertusvandepoll** [gdepourtales/ng-cells#25]
I am very pleased with your ng-cells directive: it's high performant and flexible, much better than other jquery or ng stuff that I have tried. There is just one issue that I would like you to know: the mouse wheel scroll on the table works on Chrome, IE and Opera but not on FireFox 37.0.1 nor on Safari 5.1.7 (on Windows 8.1). Mousewheel in Safari on the Mac works fine. Any ideas how to fix that?

**Comment by kayhadrin** [comment]
what's the version that's affected?

**Comment by bertusvandepoll** [comment]
the latest version: 0.3.9

**Comment by kayhadrin** [comment]
Ok, I'll have a look into this.

**Comment by kayhadrin** [comment]
Thanks for reporting this issue.
I found its cause and raised a new PR.

**Comment by bertusvandepoll** [comment]
Thank you: issue is fixed!
