### ISSUE TITLE
Merge Cells

### ISSUE THREAD

**Issue by rasekar2000** [gdepourtales/ng-cells#31]
Hello,

 We have rowspan / colspan options for merging Cells in HTML Tables...

 Can you please bring that in ng-cells as well.

Thanks and Regards,
Raj

**Comment by kayhadrin** [comment]
Hum, that's seems like a very complex use case.

What would your use case be?

**Comment by rasekar2000** [comment]
Hi @kayhadrin ,
To allow the user to feed the information for a Template .. 
Template is dynamic as such the rows / columns can be merged ... Then this template output will be shown in another place..

Regards,
Raj

**Comment by kayhadrin** [comment]
To be honest, I don't have the need to do this and I'm yet to hear from the
project own if this is something he'd envisage implementing.

The best you can do is ask, and additionally, analyse this as far as pure
logic can go before someone tries to implement this.

As you probably already know, the ng-cells directive is designed to show
data from a 2D data table. If you want to display some cells with a
colspan/rowspan greater than one, then you would need to define a set of
rules to decide what data cell to use for the cell content.
What would that be?

Also, how could we define the coordinates of the merged cells?

**Comment by rasekar2000** [comment]
No Issues.. I could use the functionality from ngHandsonTable.
Thanks for your time.
Regards,
Raj
