### ISSUE TITLE
10 $digest() iterations reached. Aborting!

### ISSUE THREAD

**Issue by thellvig** [gdepourtales/ng-cells#35]
First of all, thank you very much for creating and sharing ng-cell!

I am ocassionally getting this error, but not able to isolate it cause. Any suggestion?

**Comment by gdepourtales** [comment]
Hum. Difficult to understand without seeing your code. Can you create an example in plunkr which basically mimics your code ?

**Comment by thellvig** [comment]
Hi
Thank you responding . It turns out that I have accidently  removed ng 
cell.css and not noticed for a while. Once included issue resolved.

Sorry about the false alarm .

Thank you again for sharing ng cell.

Best regards
Tibor Hellvig

Sent with AquaMail for Android
http://www.aqua-mail.com
